### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by jkleiser** [nicolas-p/skov#10]
I see here http://rosettacode.org/wiki/Time_a_function#Factor that Factor has a `time` word that can tell the running time (and more) of an expression. How can one do this in Skov? When I entered the `time` word in Skov, I could see no output connector.

**Comment by kustomzone** [comment]
There's a full description in the docs under Timers.

**Comment by nicolas-p** [comment]
```time``` has no output connector because it displays its result like ```display```.

But it doesn't work because there must be a bug in the way I handle quotations. (I had never considered quotations that don't return anything.)

<img width="171" alt="capture d ecran 2016-12-05 a 13 10 25" src="https://cloud.githubusercontent.com/assets/11431580/20884643/bc3351b6-baec-11e6-953a-78231ec04102.png">

**Comment by nicolas-p** [comment]
I fixed the bug in d4fd390d285a91ffd8db94cf3aa3363a723900d8

```time``` works perfectly now.

**Comment by nicolas-p** [comment]
If you want an output connector, you can use ```benchmark``` (I've just discovered it.)
