### ISSUE TITLE
Cannot enter '>upper' word

### ISSUE THREAD

**Issue by balazsbotond** [nicolas-p/skov#3]
I'm not sure this is the right place to report errors in the tutorial.

But as I tried following along the steps [here](http://skov.software/en/) and entered the `>upper` word, it just disappeared. I couldn't make it work in any way.

I use the latest Windows version.

**Comment by nicolas-p** [comment]
Well spotted!

In Skov, words are sorted in vocabularies (like modules in Python for example). And because there are a lot of vocabularies that won't be useful to you, only a few vocabularies are active by default.

If a vocabulary is inactive, the words inside still work normally, but you can't access them.

To get access to ```>upper```, click the `?` button and type ```>upper``` in the search box. Click the first entry. You now see the help page for this word. There is a blue circle in the top right corner of the window. Click it to activate the entire ```unicode``` vocabulary.

I should have checked that every word used in the tutorial is active by default. My mistake.

(And making the activate/deactivate button more obvious was already on my to-do list)

**Comment by nicolas-p** [comment]
I changed the tutorial so that it doesn't use ```>upper``` anymore.
